### ISSUE TITLE
CDR - Filtering broken on some columns?

### ISSUE THREAD

**Issue by nealcoffey** [VoicePulse/FIVE-Portal#40]
Tried adding a filter under "Cost" set to "Greater than 0.05" - rows with cost under that amount still show. Tested other columns and found:

* Rate > 0.01 - OK
* Without clearing the Rate filter, added Duration > 500. Did not work. Also, rates below 0.01 showed up again. It appears having two filters canceled each other out?
* Cleared the Rate filter, and then the Duration filter did work.
* Added a Source filter for a number that exists in the CDR. This seems to coexist with the Duration filter correctly.

Seems problems might be only around the columns with floating-point data?

**Comment by ravisakaria** [comment]
Saw corresponding exception logged in API logs.  This should be fixed as of API deployment 1.0.181.

**Comment by ravisakaria** [comment]
@nealcoffey Can you verify whether or not this is fixed?  Thanks.

**Comment by ravisakaria** [comment]
@nealcoffey ..following up on this.  Can we close it?

**Comment by nealcoffey** [comment]
@ravisakaria CDR filtering appears to work correctly. I can't break it by mixing multiple filters, anyway.
