### ISSUE TITLE
Edit Phone Number Page UI

### ISSUE THREAD

**Issue by monicahaley** [VoicePulse/FIVE-Portal#44]
E911 Enabled indicator

**Comment by monicahaley** [comment]
I think there should be a "Are you sure you want to remove this phone number?" type of message when you click Remove from Org. 

Also, I almost clicked on the remove button when I meant to click Save Changes. Distancing it would be helpful, but an "Are you sure?" message would take care of accidentally removing a DID also.

**Comment by ravisakaria** [comment]
Closed via commit fa84fbea25a0d311fd5c0bb1a610ce0d6bffaa2a
