### ISSUE TITLE
Where to Register to

### ISSUE THREAD

**Issue by VinnyVoicePulse** [VoicePulse/FIVE-Portal#47]
Customers can't tell where to register to anymore on their gateway or endpoint tab. Before we used to say on the gateway tab and endpoint tab that customers should register to their hostname.proxy.voicepulse.com. Customers don't see this anymore anywhere so they never know where they should register to anymore.

**Comment by ravisakaria** [comment]
Info is available on the Edit Endpoint page now, but I'm working on displaying it in other places as well.

**Comment by ravisakaria** [comment]
To summarize so far, it's now visible on the Edit Endpoint page, and the Create Gateway and Edit Gateway (right above the hostname fields).  Still working on even more clarity.

**Comment by ravisakaria** [comment]
Added info box at top of the Edit Endpiont page.
