### ISSUE TITLE
Need Help article for Balance Alerts & Thresholds

### ISSUE THREAD

**Issue by ravisakaria** [VoicePulse/FIVE-Portal#67]
The Manage Alerts & Thresholds page has a help link that currently just points to help.voicepulse.com.  We need an article explaining the details of the options on that page, and then need to change the link to point to that new article.
@nealcoffey write the article and then we'll change the link.

**Comment by nealcoffey** [comment]
@ravisakaria Writing this article now when I noticed the following inconsistency:

* Manage Balance & Usage Alerts (sidebar menu)
* Manage Balance Alerts & Thresholds (heading on page)

One of these should probably change to match. Given you wrote "Balance Alerts & Thresholds" on this issue, is that the one we'll go with?

**Comment by nealcoffey** [comment]
Article written. Someone should double-check my descriptions of the features are accurate.

**Comment by ravisakaria** [comment]
Looks good.  Thank you.
