### ISSUE TITLE
Saving App Map works but displays "There was an error. Please try again."

### ISSUE THREAD

**Issue by nealcoffey** [VoicePulse/FIVE-Portal#89]
This may have something to do with the ridiculous names I've been saving things under, I'm not sure. But when saving my App Map I get a popup with the message "There was an error. Please try again." However, if I click to another page and come back to Call Flow, or just refresh the page, it appears the App Map was saved correctly.

This is in the My Company organization belonging to vpfivedemo@voicepulse.com

Edit: Safari 8.0.5 (latest)

**Comment by rickyhartmann** [comment]
This was resolved in the commit referenced above
